sudo: required
addons:
  apt:
    packages:
    - curl
    - xsltproc
language: erlang
services:
  - docker
otp_release:
- 17.5
cache:
  apt: true
before_install:
- ((ps aux |grep [r]abbit) || /bin/true)
- ((sudo service rabbitmq stop) || /bin/true)
- mkdir -p bin
- curl -Ls -o bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
- curl -Ls -o bin/rebar https://github.com/rebar/rebar/releases/download/2.6.1/rebar
- chmod u+x bin/rebar bin/rebar3
- export PATH=$PATH:$PWD/bin
- pip install --user codecov
before_script:
- (test "$TRAVIS_TAG" && git checkout "$TRAVIS_TAG") || (test "$TRAVIS_BRANCH" && git checkout "$TRAVIS_BRANCH")
script: rebar3 eunit
after_success:
- covertool -cover _build/test/cover/eunit.coverdata -appname rabbitmq-autocluster -output cobertura.xml
- codecov
before_deploy:
- make clean
- make dist
- tar cvfz autocluster-${TRAVIS_TAG}.tgz plugins/autocluster-${TRAVIS_TAG}.ez plugins/rabbitmq_aws-*.ez
- echo "TRAVIS_OTP_RELEASE = ${TRAVIS_OTP_RELEASE}"
deploy:
  provider: releases
  file: autocluster-${TRAVIS_TAG}.tgz
  skip_cleanup: true
  on:
    condition: "$TRAVIS_OTP_RELEASE = 17.5"
    tags: true
    repo: bargenson/rabbitmq-autocluster
env:
  global:
  - secure: e7s0dAfWlq2IG1oFdKoR7e5j4EE94qTwqiXBiV+C9SdjNGUWbSbUS4ddY9izzmJIZdS3968cnqP3h1/qgY1Lr0hrBLRSQEmaP2sW8xKgOyscH553octRt4UdpnLZA1QChVRzRjEg36C7dsXoOOmc4V5Qsuq0VvihWXH533qqkt0t471Q3cFfhyrKTWNk9er1RULUrTpjToMv4w8vzrRaLrCvji6/+kekeup5IktvUYaHyZDd8EbbYv494VoDKpFnfzUQkFSb3hkYXg5Pr/HsJjJzU8ewzmvLiSLWxexG596lpNjVB/zI4e0Tqh94m9z3M+gK0TxzJ6K2RB2EvjATKVdTAgygPtzN3pVjU0fADzQteeVfTUXrLy5NPPf9SVeSDTU3vQdPF+ZFdwzc+v9sbqeJKNVmP03hvYefS6f5NoWBBqR8VvyfVh6X+7/8XNvG8kxwJbPwL6A98u5mHEznhf7hEJkocOB9ehIffYwNfPP39J7zR9HmR3mVfsABV3DV4fYy9dsXu2aQiuoMd1VAvY2zY0KA5nDc7O3e/Wx1+CIP1J6Ry0UGSPdHEdwkz2+73yDf39mkSLodznvBKWeIs8Gk+Wp8AE3oMVTP5z3xr+rp5WBuq9G/vT4d387cj6J/T+y89tJ9AO5CVa4XLFLULy0/E5ug6hPPVtXn64NsX2o=
  - secure: an5VN1cYq5549HjfGxtykJg3ArykTmM/xiQI1bsCnOPUfrH/Nxz8LynYVlUeeBUSfpcQkek1OiSBCIxeQ4R9UP8YcJh2i82Pvzp5vz3CnsOIV3KqCTSNGcqUlu9OH2HsAU4dShGr6J5+8rQ6b1RHm5PwEu6XAIDN88xd0rOU7RjjafecZ8+WYAdNxCDwd86CFQKkhEeHmH2/yeaElnhpNBuyrBTHuHoYEhdlpxh7pZmSKlciHaE8hDgxdVxoEJRE8hLDV+uAxKzaIFEET58EbXmjQBiho+xEYDobbvOG66x7Tgt/f4egb8XLlGVO+6hUGJc7OZ+MJRsXaumu5CezggvjL8FBFTtkNHPGvmRKv+x18U2cVZ3YWr9bhMmIJVP2cVl6Vct9cLiTYjhTKaziXhs5qy9i6QLOWbLg8KHi3aPPwrN7dILU+des/Y5/IRsV+vDwr/UQj9mhF6yFwRqiw5qKbw08bqeL1NRGuEh0PT0nuevcIm2vd9Q2+QBirfU4SZ9zkcdwlv0ZyliNkgy6/zeKEdTxTWpD7n8ok5+1z/HuZcloTl81wjsj04hWuD8tcnZoBYnSR7+SmzqEDpawDg501ccXta0bqzcylKX1OhpFQ0YPM2xNGW+qGRcrNHPTJAiKYrW1ibzAKJKH85SlN7iPUKcgLj77AsIT/mh7AP0=
  - secure: wB1TNCJ3paPjAqiphZshfB02HZ/ETOOkSBoTSxK2+xLb1jZJ1u1mEgfzMvNNtOB0n/ZFsNg1wIwHBh6ceXBZ60FZlwD9swyjmGIUCToANlorigqMv4Ml6srbmacB6MVqCN4b/W3RMm291fi2oyK8oaNzWdjwsaePAQUfRSJaMkfv0ZXXNftHZI59+mxWb7nuZXEr/r2HcNjOECx/l/X7Qe6vMbpfCdLyryzUSDdIzhUhTjtxwaOQqRkj52Gt4Z9jzmaYibJLnIQfjGjrpBu+ymAZPCgd5M+3ettdLtneH/qMDiTlOXm4I9XX8gH326y1YFn2T9rbu2RqNI3T3SKqSN7BlYtEIGk0/SGXikiGK2Wu/aCOLp4oh5N6nVIV2Egcl1tNZ+meozDHmxy2MyBzr4qGfCJl6GIGNrUo8d1yvcZIyjDWar2KMJ9zGKpFcNEwaZOXTRXISbC8HtBAaPL65fhEkqHBtuRReV3OAQY3LyrVj1tllsjM7BB4UXcjUSwiWAPOrEZV7bMGiupyOCuRBT06ENIezu2rIapDExZKxuHaFx6LNyw8HSUCfeCSpQIyvlr9v7o0U2GBkfLegnbKzTvsb7xEV8GbgfTQ177brCPsy3sMTsQ7NV6VVL8RLa/t5dq+GIWwBPKE/zOP9ZPHYg7VxP2oNOqAcMe+cFI5zg4=
